# We want to use the KVM-based system, so require sudo
sudo: required

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/verbose/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

services:
  - docker

before_install:
  - git clone https://github.com/discourse/discourse-plugin-ci

install: true # Prevent travis doing bundle install

script:
  - discourse-plugin-ci/script.sh